_target_: src.datamodules.text.TextModule
train_path: ${root_dir}/data/wikitext-103/train.npy
val_path: ${root_dir}/data/wikitext-103/validation.npy
test_path: ${root_dir}/data/wikitext-103/test.npy
max_seq_len: 512
train_epoch_size: 100_000
val_epoch_size: 1000
batch_size: 10
num_workers: 2
pin_memory: True
